name: Deploy documentation

on:
  push:
    branches: [main]
  workflow_dispatch:


concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build documentation
        uses: withastro/action@e84f40bd8d2caa9e768ec82ad30dd81f0b280853 # v6
        with:
          path: .
          package-manager: bun
          build-cmd: bun run --filter=docs lint && bun run --filter=docs typecheck && bun run build:docs
          cache-dir: docs/node_modules/.astro
          out-dir: docs/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
